import { theme } from "@/styles/themes.css";

import { type GroupListType } from "@/api/groups/type";
import type { NotificationSettingContent } from "@/api/notifications/type";
import { NOTIFICATION_SETTINGS_COLUMNS } from "@/view/user/setting/NotificationSetting/NotificationSettingTable/constant";
import { tdStyle } from "@/view/user/setting/NotificationSetting/NotificationSettingTable/index.css";
import { STUDY_LIST_COLUMNS } from "@/view/user/setting/StudyList/StudyListTable/constant";
import {
  tableCaptionStyle,
  tableStyle,
  theadStyle,
} from "@/view/user/setting/StudyList/StudyListTable/index.css";
import type { Meta } from "@storybook/react";
import { DataTable } from ".";

const meta: Meta<typeof DataTable> = {
  title: "Shared/Table",
  component: DataTable,
  parameters: {
    design: {
      type: "figma",
      url: "https://www.figma.com/design/PBHmaVSKndAId6lY6G2qEb/AlgoHub?node-id=491-25321&t=kXe0v1ggMwRlTf9d-4",
    },
  },
  tags: ["autodocs"],
  decorators: (Story) => (
    <div style={{ backgroundColor: theme.color.bg }}>
      <Story />
    </div>
  ),
} satisfies Meta<typeof DataTable>;
export default meta;

const StudyListData: GroupListType[] = [
  {
    id: 5,
    name: "떡잎마을 방범대",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/90c7df07-2a2e-4a07-a8e9-501d44b5da0cjeremy-thomas-jh2KTqHLMjE-unsplash.jpg",
    startDate: "2023.06.01",
    endDate: "2023.12.31",
    introduction: "떡잎마을 방범대 코테 화이팅!",
    ownerNickname: "gamzaKing",
    role: "ADMIN",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 8,
    name: "나는 최주용 !",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/0ac44dc3-b971-45a3-a918-878c17270dd5%C3%A1%C2%84%C2%8E%C3%A1%C2%85%C2%AC%C3%A1%C2%84%C2%8C%C3%A1%C2%85%C2%AE%C3%A1%C2%84%C2%8B%C3%A1%C2%85%C2%AD%C3%A1%C2%86%C2%BC.png",
    startDate: "2024.12.05",
    endDate: "2024.12.05",
    introduction: "나는 최주용 !",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
  },
  {
    id: 15,
    name: "test group",
    groupImage: null,
    startDate: "2024.11.12",
    endDate: "2024.11.29",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 16,
    name: "string",
    groupImage: null,
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 17,
    name: "This is Choi",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/117c3153-a263-499a-a8c9-551e1a9a590dTypeScript.png",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    introduction: "choi ju yong",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 18,
    name: "최주용",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/537472da-b8ba-4c0b-8b8b-12fd545038d4%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%B5%E1%86%AF%20%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB.png",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    introduction: "최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 19,
    name: "최주용",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/973eee09-78f3-48dc-9ee2-136694465dcc%E1%84%80%E1%85%B5%E1%86%BA%E1%84%92%E1%85%A5%E1%86%B8%20%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%A1%E1%84%8B%E1%85%B5%E1%86%AF.jpeg",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    introduction: "최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 20,
    name: "최주용",
    groupImage: null,
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    introduction: "최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 23,
    name: "testgroup",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/4d0c6706-d703-46a0-812e-00b233886a5beberhard-grossgasteiger-NvesrDbsrL4-unsplash.jpg",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 24,
    name: "string",
    groupImage: null,
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 25,
    name: "string",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/ab754e85-cdea-4f0b-bc13-be47ffdfdda0%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%B5%E1%86%AF%20%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB.png",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 26,
    name: "string",
    groupImage: null,
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 28,
    name: "string",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/d4a19b59-7620-423a-9f0a-92f53c975591IMG_3356.HEIC",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 29,
    name: "string",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/95179f16-f5e0-44f9-acb0-466c9a6f5d18IMG_3356.HEIC",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 30,
    name: "string",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/0a7cd578-86e7-42c9-9881-7a7260dfc94fIMG_3356.HEIC",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 31,
    name: "string",
    groupImage: null,
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 32,
    name: "테스트 스터디 그룹",
    groupImage: null,
    startDate: "2024.11.15",
    endDate: "2024.11.25",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 33,
    name: "adsfadsf",
    groupImage: null,
    startDate: "2024.11.12",
    endDate: "2024.11.16",
    introduction: "asdfasdfad",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 34,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.05",
    endDate: "2024.11.16",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 35,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.05",
    endDate: "2024.11.16",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 36,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.05",
    endDate: "2024.11.16",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 37,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.17",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 38,
    name: "이제는 좀 돼라 ?",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/150bcdfa-26b3-4ec4-b3f9-420c275da473%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%B5%E1%86%AF%20%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB.png",
    startDate: "2024.11.11",
    endDate: "2024.11.17",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 39,
    name: "이제는 좀 돼라 ?",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/ab5dd5dd-220c-4e33-85f3-2f3c4aa78b54%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%B5%E1%86%AF%20%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB.png",
    startDate: "2024.11.11",
    endDate: "2024.11.17",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 40,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.17",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 41,
    name: "최주용 나는 최주용",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/06c365c4-75b9-4f41-a6ac-648453b346baKakaoTalk_Photo_2024-05-09-13-42-00.png",
    startDate: "2024.11.20",
    endDate: "2024.11.23",
    introduction: "최주용 나는 최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 42,
    name: "최주용 최주용",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/321a756d-b356-438a-aa51-856a9371979eKakaoTalk_Photo_2024-05-09-13-42-00.png",
    startDate: "2024.11.20",
    endDate: "2024.11.23",
    introduction: "최주용 최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 43,
    name: "최주용 나는 최주용",
    groupImage: null,
    startDate: "2024.11.21",
    endDate: "2024.11.24",
    introduction: "최주용 나는 최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 44,
    name: "올바르게 뜨렴",
    groupImage: null,
    startDate: "2024.11.19",
    endDate: "2024.11.22",
    introduction: "올바르게 뜨렴",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 45,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.16",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 46,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.16",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 47,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.16",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 48,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.16",
    introduction: "이제는 좀 돼라 ?",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 49,
    name: "ㅊㅈㅇㅊㅈㅇ",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/fb2cd4f7-40f1-44c1-b765-35b8e574490fKakaoTalk_Photo_2024-04-21-21-07-40%20004.jpeg",
    startDate: "2024.11.13",
    endDate: "2024.11.20",
    introduction: "ㅊㅈㅇㅊㅈㅇ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 50,
    name: "토스트 확인용",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/8509874e-0178-4c97-ac38-b7af65d12eaetiki.png",
    startDate: "2024.11.03",
    endDate: "2024.11.16",
    introduction: "토스트 확인용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 51,
    name: "최주용",
    groupImage: null,
    startDate: "2024.11.10",
    endDate: "2024.11.22",
    introduction: "sdfadsfasf",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 52,
    name: "최주용 최주용 최주용",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.21",
    introduction: "최주용 최주용 최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 53,
    name: "teststest",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "string",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 54,
    name: "최주용",
    groupImage: null,
    startDate: "2024.11.13",
    endDate: "2024.11.17",
    introduction: "최주용최주용최주용최주용최주용최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 55,
    name: "sadfasdfasdfa",
    groupImage: null,
    startDate: "2024.11.12",
    endDate: "2024.11.24",
    introduction: "sadfasdfasdf",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 56,
    name: "asdfsadf",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "asdfadsf",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 59,
    name: "최주용",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.21",
    introduction: "최주용최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 60,
    name: "최주용 최주용",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "최주용 최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 61,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㅁㄹ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 62,
    name: "ㅊㅈㅇㅊㅈㅇ",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "ㅊㅈㅇㅊㅈㅇ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 63,
    name: "최주용 최주용",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "최주용 최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 64,
    name: "인하대학교 스터디 그룹",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.12",
    introduction: "하이하이",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 65,
    name: "인하대학교 스터디 그룹",
    groupImage: null,
    startDate: "2024.11.11",
    endDate: "2024.11.12",
    introduction: "하이하이",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 66,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 67,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 68,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 69,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 70,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 71,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 72,
    name: "이제는 좀 돼라 ?",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "sadfdsafdf",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
  },
  {
    id: 73,
    name: "sdafsadfasdf",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "sadfasdfdsaf",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 74,
    name: "ㅊㅈㅇ",
    groupImage: null,
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    introduction: "ㅊㅈㅇ",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 75,
    name: "adsfasdfd",
    groupImage: null,
    startDate: "2024.11.21",
    endDate: "2024.11.23",
    introduction: "asdfasdfasdf",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 76,
    name: "최주용",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/dc5cdbd8-f504-4476-a42f-6e52d3d997b6KakaoTalk_Photo_2024-04-08-16-43-59.jpeg",
    startDate: "2024.11.11",
    endDate: "2024.11.24",
    introduction: "최주용과 꾸리",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 78,
    name: "나는야 주용",
    groupImage: null,
    startDate: "2024.11.18",
    endDate: "2024.11.22",
    introduction: "나는야 주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 79,
    name: "최주용",
    groupImage: null,
    startDate: "2024.11.28",
    endDate: "2024.11.30",
    introduction: "최주용",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 82,
    name: "왜 그룹 수정은 안되냐고 !",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/41e9425e-5f61-4faa-b7e7-4dda5963b313%E1%84%83%E1%85%A1%E1%84%8B%E1%85%AE%E1%86%AB%E1%84%85%E1%85%A9%E1%84%83%E1%85%B3.jpeg",
    startDate: "2024.11.11",
    endDate: "2024.11.23",
    introduction: "왜 그룹 수정은 안되냐고 !",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 84,
    name: "jnary 찬양 스터디",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/7e8eb0cf-85a5-4c21-a375-70a2582b1645IMG_0102.jpeg",
    startDate: "2024.11.23",
    endDate: "2024.11.23",
    introduction: "",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
  {
    id: 87,
    name: "jnary 찬양 스터디",
    groupImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/c213fac9-5780-4b9f-92d8-df6f15f2e059IMG_0102.jpeg",
    startDate: "2024.11.23",
    endDate: "2024.11.23",
    introduction: "",
    ownerNickname: "rladmstn",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
  },
];

export const StudyList = {
  render: () => {
    return (
      <DataTable
        title="스터디 리스트"
        rows={StudyListData}
        cols={STUDY_LIST_COLUMNS}
        tableClassName={tableStyle}
        captionClassName={tableCaptionStyle}
        theadClassName={theadStyle}
      />
    );
  },
};

const NotificationSettingData: NotificationSettingContent[] = [
  {
    groupId: 15,
    groupName: "test group",
    allNotifications: false,
    newProblem: true,
    newSolution: false,
    newComment: true,
    newMember: false,
    deadlineReached: false,
  },
  {
    groupId: 16,
    groupName: "string",
    allNotifications: false,
    newProblem: false,
    newSolution: false,
    newComment: false,
    newMember: false,
    deadlineReached: false,
  },
  {
    groupId: 17,
    groupName: "This is Choi",
    allNotifications: false,
    newProblem: false,
    newSolution: false,
    newComment: false,
    newMember: false,
    deadlineReached: false,
  },
  {
    groupId: 18,
    groupName: "최주용",
    allNotifications: false,
    newProblem: false,
    newSolution: false,
    newComment: false,
    newMember: false,
    deadlineReached: false,
  },
  {
    groupId: 19,
    groupName: "최주용",
    allNotifications: false,
    newProblem: false,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 20,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 23,
    groupName: "testgroup",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 24,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 25,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 26,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 28,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 29,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 30,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 31,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 32,
    groupName: "테스트 스터디 그룹",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 33,
    groupName: "adsfadsf",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 34,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 35,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 36,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 37,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 38,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 39,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 40,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 41,
    groupName: "최주용 나는 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 42,
    groupName: "최주용 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 43,
    groupName: "최주용 나는 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 44,
    groupName: "올바르게 뜨렴",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 45,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 46,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 47,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 48,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 49,
    groupName: "ㅊㅈㅇㅊㅈㅇ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 50,
    groupName: "토스트 확인용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 51,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 52,
    groupName: "최주용 최주용 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 53,
    groupName: "teststest",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 54,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 55,
    groupName: "sadfasdfasdfa",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 56,
    groupName: "asdfsadf",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 59,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 60,
    groupName: "최주용 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 61,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 62,
    groupName: "ㅊㅈㅇㅊㅈㅇ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 63,
    groupName: "최주용 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 64,
    groupName: "인하대학교 스터디 그룹",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 65,
    groupName: "인하대학교 스터디 그룹",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 66,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 67,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 68,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 69,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 70,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 71,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 72,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 73,
    groupName: "sdafsadfasdf",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 74,
    groupName: "ㅊㅈㅇ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 75,
    groupName: "adsfasdfd",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 76,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 78,
    groupName: "나는야 주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 79,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 80,
    groupName: "알고헙 릴리즈 언제해",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 82,
    groupName: "왜 그룹 수정은 안되냐고 !",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 84,
    groupName: "jnary 찬양 스터디",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 87,
    groupName: "jnary 찬양 스터디",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 8,
    groupName: "나는 최주용 !",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 89,
    groupName: "그룹 탈퇴해봐 주용아",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
];

export const NotificationSetting = {
  render: () => {
    return (
      <DataTable
        rows={NotificationSettingData}
        cols={NOTIFICATION_SETTINGS_COLUMNS}
        tableClassName={tableStyle}
        theadClassName={theadStyle}
        tdClassName={tdStyle}
      />
    );
  },
};
