name: Assign Reviewer

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
