name: Development Deploy

on: 
  push:
    branches:
        - deploy

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Restore cache
        uses: actions/cache@v4
        with:
            path: |
              .next/cache
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
            restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml') }}-

      - name: Build with Next.js
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: build-app
          path: .next
