name: rc-deploy

on:
  push:
    branches:
      - main
  
jobs:
  rc-deploy:
    uses: ./.github/workflows/deploy.workflow.yml
    secrets:
      CREDENTIAL_NAME: ${{ secrets.CREDENTIAL_NAME }}
      CREDENTIAL_PW: ${{ secrets.CREDENTIAL_PW }}
    with:
      environment: rc
      port: 3001