name: rc-deploy

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened]
  
jobs:
  rc-deploy:
    if: contains(github.event.pull_request.labels.*.name, 'rc-deploy')
    uses: ./.github/workflows/rc.deploy.workflow.yml
    secrets:
      CREDENTIAL_NAME: ${{ secrets.CREDENTIAL_NAME }}
      CREDENTIAL_PW: ${{ secrets.CREDENTIAL_PW }}
      NEXT_RC_GITHUB_ID: ${{ secrets.NEXT_RC_GITHUB_ID }}
      NEXT_RC_GITHUB_SECRET: ${{ secrets.NEXT_RC_GITHUB_SECRET }}
      NEXT_PUBLIC_RC_HOST: ${{ secrets.NEXT_PUBLIC_RC_HOST }}
      NEXT_PUBLIC_MIXPANEL_TOKEN: ${{ secrets.NEXT_PUBLIC_MIXPANEL_TOKEN }}
    with:
      NEXT_PUBLIC_APP_ENV: rc